services:
  socialmediaback:
#    image: dvan143/socialmediaback
    build:
      context: SocialMediaBack/.
    container_name: socialmediaback
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - SocialMediaBack/.env
  socialmediafront:
#    image: dvan143/socialmediafront
    build:
      context: SocialMediaFront/.
    container_name: socialmediafront
    ports:
      - "80:80"
    depends_on:
      - socialmediaback
  emailVerifier:
    image: dvan143/emailverifier
    container_name: emailVerifier
    env_file:
      - SocialMediaBack/.env
    depends_on:
      - smtpService
      - socialmediaback
      - rabbitmq
  smtpService:
    image: boky/postfix:4.4.0-debian
    container_name: smtpService
    env_file:
      - SocialMediaBack/.env
    ports:
      - "25:25"
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - SocialMediaBack/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - SocialMediaBack/.env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  postgres-data:
  rabbitmq-data: