services:
  socialmedia:
    build:
      context: .
    image: socialmedia
    container_name: socialMediaApp
    ports:
      - "80:8080"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - .env
  emailVerifier:
    image: dvan143/emailverifier
    container_name: emailVerifier
    env_file:
      - .env
    depends_on:
      - socialmedia
      - rabbitmq
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  postgres-data:
  rabbitmq-data: