services:
  socialMedia:
#  projectssite:
    image: socialmedia
#    image: dvan143/projectssite
#    container_name: projectssite
    container_name: socialMediaApp
    ports:
      - "80:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testUsername
      POSTGRES_PASSWORD: testPassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: