spring:
  datasource:
    url: jdbc:h2:mem:socialMedia
    driver-class-name: org.h2.Driver
    username: ${Db_username}
    password: ${Db_password}

  spring:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

SecretKey: ${Secret_Key}
server:
  servlet:
    context-path: /socialmedia