spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: h2
    password:

  rabbitmq:
    host: no_value
    port: 1111
    username: no_value
    password: no_value

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      example.socialmedia: INFO

server:
  servlet:
    context-path: /socialmedia
SecretKey: FSDbmnfdmsnEIUrwhfjdsjkdfsh213897123897FDJHGSJHGFDEUYWRHUGXCNBCZX
TokenMaxAge: 1