spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT}

logging:
  level:
    org:
      "springframework.security": DEBUG
      "example.socialmedia": DEBUG

server:
  servlet:
    context-path: /socialmedia
secret-key: ${SECRET_KEY}
token-max-age: ${TOKEN_MAX_AGE}